config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { registrations: 'registrations' }



  root 'home#show'


resources :home, only:[:show, :index]

  resources :users do
    resources :leads
  end

  resources :leads, only:[:index, :show] do
    resources :calls, only:[:index, :show, :create, :new]
  end

  resources :leads, only:[:index, :show] do
    resources :emails, only:[:index, :show, :create, :new]
  end

  resources :leads, only:[:index, :show] do
    resources :meetings, only:[:index, :show, :create, :new]
  end


  namespace :api do
  namespace :v1 do
    resources :users, only: [:index, :show] do
      resources :calls, only: [:index, :show]
      resources :emails, only: [:index, :show]
      resources :meetings, only: [:index, :show]
      end
    end
  end


end

app/models/lead.rb
class Lead < ApplicationRecord



  STATUS_OPTIONS = [
    ["Open/No-Activity", "Open/No-Activity"],
    ["In Process", "In Process"],
    ["Contacted","Contacted"],
    ["No Interest", "No Interest"],
    ["Call Back", "Call Back"],
    ["No Longer with Company", "No Longer with Company"],
    ["Bad Data","Bad Data"],
  ]

  validates :company, presence: true
  validates :name, presence: true
  validates :position, presence: true
  validates :phone_number, presence: true
  validates :status, presence: true, inclusion: { in: STATUS_OPTIONS.map { |status| status[1] } }
  validates :email, presence: true, uniqueness: true
  validates :user_id, presence: true





  belongs_to :user
  has_many :calls
  has_many :emails
  has_many :meetings
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
 before_action :authenticate_user!

  def index
    @leads = Lead.where(user_id: params[:user_id])
    @leads = current_user.leads
  end

  def new
    @user = current_user
    @lead = Lead.new
    @status_collection  = Lead::STATUS_OPTIONS
  end

  def show
    @lead = Lead.find(params[:id])
    @position = @lead.position
    @status = @lead.status
  end

  def create
    @user = current_user
    @lead = Lead.new(lead_params)
    @lead.user = @user
    @status_collection  = Lead::STATUS_OPTIONS
    if @lead.save
      redirect_to user_leads_path notice: "Lead added successfully"
    else
      flash.now[:alert] = @lead.errors.full_messages
      render :new
    end
  end

def edit
  @user = User.find(params[:user_id])
  @lead = Lead.find(params[:id])
  @status_collection  = Lead::STATUS_OPTIONS

end

def update
  @user = current_user
  @lead = Lead.find(params[:id])
  if @lead.update(lead_params)
    redirect_to user_lead_path(@lead), notice: "successfully updated"
  else
    render :edit
    flash.now[:alert] = "Edits not saved"
  end
end

private


def lead_params
  params.require(:lead).permit(:company, :user_id, :name, :position, :phone_number, :email, :status)
end

end

app/views/leads/edit.html.erb
<div class='edit-lead-form'>

<%= form_for [@user, @lead]  do |f| %>

    <div class= 'required-fields'>

      <% f.label :company %>
      <%= f.text_field :company, placeholder: "Company" %><br />

      <% f.label :name %>
      <%= f.text_field :name, placeholder: "Name" %><br />

      <% f.label :position %>
      <%= f.text_field :position, placeholder: "Position" %><br />

      <% f.label :phone_number %>
      <%= f.text_field :phone_number, placeholder: "Direct Dial" %><br/>

      <% f.label :email %>
      <%= f.text_field :email, placeholder: "Email" %><br />

      <% f.label :status %>
      <%= f.select(:status, options_for_select(@status_collection), {:prompt => "lead status"})%>
      <div>
        <% f.submit %>
        <button class="button">Save Updates</button>
      </div>
  <% end %>
</div>

app/views/leads/index.html.erb
<div class="container">
    	<div class="row">
			<div class="col-md-6">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">Leads Assigned to you</h3>
						<div class="pull-right">
							<span class="clickable filter" data-toggle="tooltip" title="Toggle table filter" data-container="body">
								<i class="glyphicon glyphicon-filter"></i>
							</span>
						</div>
					</div>
					<div class="panel-body">
						<input type="text" class="form-control" id="dev-table-filter" data-action="filter" data-filters="#dev-table" placeholder="Find Lead" />
					</div>
					<table class="table table-hover" id="dev-table">
						<thead>
              <tr>
                <th>Name</th>
                <th>Title</th>
                <th>Company</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Status</th>
                <th>Calls</th>
                <th>Emails</th>
                <th>Meetings</th>
              </tr>
            </thead>
            <tbody>
                <% @leads.each do |lead| %>
                <tr>
                  <td><%=link_to lead.name, user_lead_path(current_user, lead.id)%></td>
                  <td><%= lead.position %></td>
                  <td><%= lead.company %></td>
                  <td><%=link_to "<button>Call</button>".html_safe, new_lead_call_path(lead)%></td>
                  <td><%=link_to "<button>Email</button>".html_safe, new_lead_email_path(lead)%></td>
                  <td><%= lead.status %></td>
                  <td><%=lead.calls.count%></td>
                  <td><%=lead.emails.count%></td>
                  <td><%=link_to "<button>Record Meeting</button>".html_safe, new_lead_meeting_path(lead)%></td>
                  <%end%>
                </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="button">
        <div style= color: black>
      <%= link_to "Add a Lead", new_user_lead_path(current_user)%>
    </div>
      </div>

app/views/leads/new.html.erb
<h1>Add a new Lead</h1>

<div class='add-lead-form'>

  <%= form_for [@user, @lead]  do |f| %>
    <div class= 'required-fields'>
      <% f.label :company %>
      <%= f.text_field :company, placeholder: "Company"%>

      <% f.label :name %>
      <%= f.text_field :name, placeholder: "Name"%>

      <% f.label :position %>
      <%= f.text_field :position, placeholder: "Position"%>

      <% f.label :phone_number %>
      <%= f.text_field :phone_number, placeholder: "Direct Dial" %>

      <% f.label :email %>
      <%= f.text_field :email, placeholder: "Email" %>

      <% f.label :status %>

      <%= f.select(:status, options_for_select(@status_collection), {:prompt => "Lead status"})%></br>
    </br>
      <div>
        <% f.submit %>
        <button class="button" style="font-weight: bold;">Add Lead</button>
      </div>
  <% end %>
</div>

app/views/leads/show.html.erb
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
        </div>
        <table class="table table-hover" id="dev-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Title</th>
              <th>Company</th>
              <th>Status</th>
              <th>Calls</th>
              <th>Emails</th>
              <th>Meetings</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%=@lead.name%></td>
              <td><%= @lead.position %></td>
              <td><%= @lead.company %></td>
              <td><%= @lead.status %></td>
              <td><%=@lead.calls.count%></td>
              <td><%=@lead.emails.count%></td>
              <td><%=@lead.meetings.count%></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="lead-show-buttons">
      <p class = "button"><%=link_to "<button>Edit Lead Details</button>".html_safe, edit_user_lead_path(@lead.user , @lead)%></p>
      <p class = "button"><%=link_to "<button>Call</button>".html_safe, new_lead_call_path(@lead)%></p>
      <p class = "button"><%=link_to "<button>Email</button>".html_safe, new_lead_email_path(@lead)%></p>
      <p class = "button"><%=link_to "<button>Record Meeting</button>".html_safe, new_lead_meeting_path(@lead)%></p>

      </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-primary">
            <div class="panel-heading">
            </div>
            <table class="table table-hover" id="dev-table">
              <thead>
                <tr>
                  <th>Meetings</th>
                  <th>Result</th>
                  <th>Details</th>
                  <th>Next Steps</th>
                  <th>Source</th>
                </tr>
              </thead>
              <tbody>
                <%@lead.meetings.each do |meeting|%>
                <tr>
                  <td><%=meeting.created_at.strftime("%B %d %Y")%></td>
                  <td><%= meeting.result%></td>
                  <td><%= meeting.details%></td>
                  <td><%= meeting.next_steps%></td>
                  <td><%= meeting.source%></td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>




    <div class="container">
      <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#table-wrapper-calls">View Calls</button>
      <div class="row">
        <div class="col-sm-12">
          <div class="table-wrapper collapse" id="table-wrapper-calls">
          <div class="panel panel-primary">
            <div class="panel-heading">
            </div>
            <table class="table  table-hover">
              <thead>
                <tr>
                  <th>Calls</th>
                  <th>Result</th>
                  <th>Details</th>
                </tr>
              </thead>
              <tbody>
                <%@lead.calls.each do |call|%>
                <tr>
                  <td><%=call.created_at.strftime("%B %d %Y")%></td>
                  <td><%= call.result %></td>
                  <td><%= call.body %></td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
          </div>
        </div>
      </div>
    </div>


        <div class="container">
          <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#table-wrapper-emails">View Emails</button>
          <div class="row">
            <div class="col-sm-12">
              <div class="table-wrapper collapse" id="table-wrapper-emails">
              <div class="panel panel-primary">
                <div class="panel-heading">
                </div>
                <table class="table table-hover" id="dev-table">
                  <thead>
                    <tr>
                      <th>Emails</th>
                      <th>Subject</th>
                      <th>Details</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%@lead.emails.each do |email|%>
                    <tr>
                      <td><%=email.created_at.strftime("%B %d %Y")%></td>
                      <td><%= email.subject%></td>
                      <td><%= email.body%></td>
                    </tr>
                    <%end%>
                  </tbody>
                </table>
              </div>
              </div>
            </div>
          </div>
        </div>


          <div class="page">
            <nav aria-label="hidden">
              <ul class="pager">
                <li><a href=`#`>Previous</a></li>
                <li><a href="#">Next</a></li>
              </ul>
            </nav>
          </div>

app/views/leads/test.html.erb
<div class="container">
    	<div class="row">
			<div class="col-md-6">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">Leads Assigned to you</h3>
					</div>
					<table class="table table-hover" id="dev-table">
						<thead>
              <tr>
                <th>Meeting</th>
                <th>Result</th>
                <th>Source</th>
              </tr>
            </thead>
            <tbody>
                <% meetingList.each do |meeting| %>
                <tr>
                  <td><%=%></td>
                  <td><%= lead.position %></td>
                  <td><%= lead.company %></td>
                  <%end%>
                </tr>
            </tbody>
          </table>
        </div>
      </div>